version: '3.3'
services:
  front-end:
    container_name: sales-care-front-end-app
    image: sales-care-front-end-app-img
    build:
      context: ./
      dockerfile: Dockerfile

    restart: always
    ports:
      - 3001:3005 #host:container port